micronaut:
  application:
    name: car-rental

  openapi:
    info:
      title: Car Rental API
      version: 0.1
      description: API de gerenciamento de usuarios

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "0RkKUGai4SVegSkcYgwRJCL1fDDHHbdzdgPlLSAJBOBPPHTfoBENW2OWLX0BDX3TJMy3E9ws5Oy8NPcJJbPHyu"
              jca-algorithm: HmacSHA512
    intercept-url-map:
      - pattern: /auth/**
        access:
          - isAnonymous()

      - pattern: /clientes/**
        access:
          - isAnonymous()

      - pattern: /agentes/**
        access:
          - isAnonymous()

      - pattern: /swagger/**
        access:
          - isAnonymous()

      - pattern: /swagger-ui/**
        access:
          - isAnonymous()

      - pattern: /**
        access:
          - isAuthenticated()

datasources:
  default:
    db-type: postgres
    dialect: POSTGRES
    url: jdbc:postgresql://localhost:5432/carrental
    username: lucas
    password: root
    driver-class-name: org.postgresql.Driver

jpa:
  default:
    entity-scan:
      packages: com.carrental.model
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

jwt:
  secret-key: "0RkKUGai4SVegSkcYgwRJCL1fDDHHbdzdgPlLSAJBOBPPHTfoBENW2OWLX0BDX3TJMy3E9ws5Oy8NPcJJbPHyu"
  expiration-ms: 86400000