micronaut:
  application:
    name: car-rental

  openapi:
    info:
      title: Car Rental API
      version: 0.1
      description: API de gerenciamento de usuarios

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    db-type: postgres
    dialect: POSTGRES
    url: jdbc:postgresql://localhost:5432/carrental
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

jpa:
  default:
    entity-scan:
      packages: com.carrental.model
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
